api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Good defaults for REST APIs

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header